
import { Inter } from 'next/font/google'
import './globals.css'
import { CounterContextProvider } from '@/context/CounterContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'constext and hooks',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CounterContextProvider>
        {children}
        </CounterContextProvider>
        </body>
    </html>
  )
}
